class UserModel {
  final status,
      rating,
      star,
      highestRating,
      globalRank,
      countryRank,
      name,
      username,
      country,
      state,
      city,
      studentProf,
      institution,
      fullySolved,
      partiallySolved;

  UserModel({
    this.status,
    this.rating,
    this.star,
    this.highestRating,
    this.globalRank,
    this.countryRank,
    this.name,
    this.username,
    this.country,
    this.state,
    this.city,
    this.studentProf,
    this.institution,
    this.fullySolved,
    this.partiallySolved,
  });
}
